[package]
name = "diesel_enum_derive"
version = "0.1.3"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]
description = "Simple Enum derive for [Postgres only] Varchar fields"
license = "MIT"
homepage = "https://github.com/terry90/diesel-enum-derive"
repository = "https://github.com/terry90/diesel-enum-derive"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.3"
syn = { version = "0.14.4", features = ["derive"] }
proc-macro2 = "0.4.6"
heck = "0.3.0"
